### ISSUE TITLE
any reason to keep this private?

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/configs#1]
Since I'm about to add sample configs meant for development of cockpit and microscope, and since we want to be able to share them with other people interested in development, should this repo be private?

@iandobbie note that most of this repo content is on separate branches, not on master.

**Comment by iandobbie** [comment]
I am not worried about it being public. Happy to hear other people opinions.

Ian

Sent from my iPhone

On 2 Apr 2020, at 18:18, Carnë Draug <notifications@github.com> wrote:

﻿

Since I'm about to add sample configs meant for development of cockpit and microscope, and since we want to be able to share them with other people interested in development, should this repo be private?

@iandobbie<https://github.com/iandobbie> note that most of this repo content is on separate branches, not on master.

**Comment by carandraug** [comment]
It is done. The repo is now public. I will move the configs on the separate branches into master.
